### ISSUE TITLE
Homework4

### ISSUE THREAD

**Issue by JSDenis** [AgronIII/Homerwork_4#1]
Доработать адаптив на смартфонах, и чтобы не было пустой области справа: 
![image](https://user-images.githubusercontent.com/32075762/73270443-bcdfe380-41ef-11ea-8d50-40faddbe5a3e.png)

**Comment by AgronIII** [comment]
Денис, добрый вечер. Там в репазитории внутри папка SturtUp и там конечный вариант домашней работы. Или ты его и открывал? Просто в конечном варианте вроде все работает

**Comment by AgronIII** [comment]
Посмотри пожалуйста еще раз. У меня вроде работает все
